### ISSUE TITLE
Unable send text to textfield in app

### ISSUE THREAD

**Issue by pseudox07** [AppiumTestDistribution/appium-flutter-integration-driver#100]
I have been trying to send text to a text field in a Sample App.  Similar issue with #96,  I have attached the sample [app file ](https://gist.github.com/pseudox07/2323e70b3fe68b3bde052c67d3ba015d)

Below are my codes and logs
[logs 1.txt](https://github.com/user-attachments/files/17185217/logs.1.txt)

Codes 
`
describe("Launch App and check for elements", () => {
  it("should enter the text", async () => {

    try {
      const title = await browser.flutterByValueKey$("txt_text_field");
      title.isDisplayed();
      title.click();
      await browser.flutterByValueKey$("txt_text_field").addValue("12345");
    } catch (error) {
      console.error("Error adding username:", error);
    }`

I called the addValue function but not API request on sending the text value to the Appium in the log.

**Comment by sudharsan-selvaraj** [comment]
What happens if you call `await title. addValue("12345");`

**Comment by pseudox07** [comment]
I still couldn't see the API request to send the text using below codes
![image](https://github.com/user-attachments/assets/37b2a681-8b6b-491d-bed1-08b8ae02b1f0)

and got error

`[AppiumDriver@9743] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
    at JWProxy.command (/Users/ec2-user/moneyx_automation/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)`

below are full log

[logs 2.txt](https://github.com/user-attachments/files/17186074/logs.2.txt)

**Comment by saikrishna321** [comment]
@pseudox07 The logs say anything about the issue you are mentioning. 

```
 Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
```

driver is quit and then you are trying to accessing the session. Please check client code that after deleteSession is called you need to create a new session.

**Comment by pseudox07** [comment]
I suspected the session is stopped and deleted once we send the keys due to crash when below errors are thrown during addValue function is being called,

> Error adding username: Error: Malformed type for "text" parameter of command elementSendKeys
[0-0] Expected: string
[0-0] Actual: object
[0-0]
[0-0] For more info see
https://w3c.github.io/webdriver/#dfn-element-send-keys
[0-0]
[0-0] at Element.protocolCommand (/Users/ec2-user/automation/node_modules/webdriver/build/index.js:1458:15)
[0-0] at Element.wrapCommandFn (/Users/ec2-user/automation/node_modules/@wdio/utils/build/index.js:1370:32)
[0-0] at async Element.wrapCommandFn (file:///Users/ec2-user/automation/node_modules/wdio-flutter-by-service/node_modules/@wdio/utils/build/shim.js:90:29)

I am not sure what you mean on the client code, can you help to have a look on the config file and the 
[Automation](https://gist.github.com/pseudox07/4b60eb604ac680242103a0b88d6fb418)

**Comment by sudharsan-selvaraj** [comment]
@pseudox07 I have published a new version of `wdio-flutter-by-service`. Could you please give it a try with v1.1.0?

https://github.com/AppiumTestDistribution/appium-flutter-integration-driver/issues/108#issuecomment-2655438894
