### ISSUE TITLE
Unable to test on real device due to port issue

### ISSUE THREAD

**Issue by suryak-cs** [AppiumTestDistribution/appium-flutter-integration-driver#102]
I have the flutter app with all the necessary configuration such as integration_test/appium_test.dart file. When I built and run the app using the following command `flutter run ios --target integration_test/appium_test.dart --flavor qa --release` I see the following lines in the terminal

```
flutter: [APPIUM FLUTTER]  Appium flutter server is listening on port 9000
flutter: 00:00 +0: appium flutter server
``` 
So far so good. 

And in my automation script in the desired caps, I have also made sure to use 
`"appium:flutterSystemPort", 9001`

When I run the test,  I see 9001 port number is NOT reachable. See the logs below.

```
[5211e896][AppiumFlutterDriver@d4bb] Checking if flutter server is running on port 9001
[5211e896][WD Proxy] Matched '/status' to command name 'getStatus'
[5211e896][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9001/status] with no body
[5211e896][iProxy@00008030:9001] Connection was refused to port 9001
[5211e896][WD Proxy] socket hang up
[5211e896][AppiumFlutterDriver@d4bb] FlutterServer not reachable on port 9001, Retrying..
[5211e896][WD Proxy] Matched '/status' to command name 'getStatus'
[5211e896][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9001/status] with no body
[5211e896][iProxy@00008030:9001] Connection was refused to port 9001
[5211e896][WD Proxy] socket hang up
```
It keeps on scanning for next port numbers like 9002, 9003 etc but to no avail. 

My dev code has 
```
dev_dependencies:
  appium_flutter_server: 0.0.27
```
and I am using latest version of appium `v2.12.1`, Java client is `9.3.0` and flutter integration version `flutter-integration@1.1.3 (automationName 'FlutterIntegration')`. 

What's wrong with my setup?

To the contrary if I clone `appium-flutter-server` repo and change the file `server.dart`, line # 39 to `const PORT_RANGE = [9001, 9020];` and have the server location referred in pubsec.yaml as 
```
  appium_flutter_server:
    path: ../server
```
127.0.0.1:9001 is reachable and rest everything works fine.

This is just the workaround. 

Please let me know the ideal fix for this situation. 
Thanks!

**Comment by lmendes21** [comment]
+1 for this issue

**Comment by sudharsan-selvaraj** [comment]
@suryak-cs could you share the full appium server logs as gist?

**Comment by suryak-cs** [comment]
`
[4c6aaf53][XCUITestDriver@6fd1] Got derived data root: '/Users/MOHAPSX18/node_modules/appium-xcuitest-driver/node_modules'
[6d101bc9][Xcode]     t =    40.60s Open com.abbott.hf.hmt-clinical.qa.ios
[6d101bc9][Xcode]     t =    40.60s     Launch com.abbott.hf.hmt-clinical.qa.ios
[6d101bc9][Xcode]     t =    40.78s         Setting up automation session
[6d101bc9][Xcode] 2025-01-29 10:05:51.574829-0800 WebDriverAgentRunner-Runner[827:105180] Waiting up to 10s until com.abbott.hf.hmt-clinical.qa.ios is in idle state (including animations)
[6d101bc9][Xcode]     t =    40.88s         Wait for com.abbott.hf.hmt-clinical.qa.ios to idle
[4c6aaf53][XCUITestDriver@6fd1] Got response with status 200: {"value":{"sessionId":"97F57F0C-D7DA-4A10-B74F-2FE8EBD6C4EA","capabilities":{"sdkVersion":"17.5.1","device":"ipad"}},"sessionId":"97F57F0C-D7DA-4A10-B74F-2FE8EBD6C4EA"}
[4c6aaf53][XCUITestDriver@6fd1] Determined the downstream protocol as 'W3C'
[4c6aaf53][XCUITestDriver@6fd1] WDA session startup took 2465ms
[4c6aaf53][XCUITestDriver@6fd1] Event 'wdaSessionStarted' logged at 1738173952770 (10:05:52 GMT-0800 (Pacific Standard Time))
[4c6aaf53][XCUITestDriver@6fd1] Event 'wdaStarted' logged at 1738173952770 (10:05:52 GMT-0800 (Pacific Standard Time))
[4c6aaf53][BaseDriver] The value of 'elementResponseAttributes' setting did not change. Skipping the update for it
[4c6aaf53][BaseDriver] The value of 'shouldUseCompactResponses' setting did not change. Skipping the update for it
[4c6aaf53][DevCon Factory Device Farm] Requesting connection for device 00008030-001205CC0AF3C02E on local port 9002, device port 9001
[4c6aaf53][DevCon Factory Device Farm] Cached connections count: 0
[4c6aaf53][DevCon Factory Device Farm] Successfully requested the connection for 00008030-001205CC0AF3C02E:9002
[4c6aaf53][AppiumFlutterDriver@2f53] Checking if flutter server is running on port 9001
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9001
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9001
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9001
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9001
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9001
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9001
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9001
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9001

....
....
....
[4c6aaf53][DevCon Factory Device Farm] Cached connections count: 0
[4c6aaf53][DevCon Factory Device Farm] Requesting connection for device 00008030-001205CC0AF3C02E on local port 9002, device port 9020
[4c6aaf53][DevCon Factory Device Farm] Cached connections count: 0
[4c6aaf53][iProxy@00008030:9002] The connection has been closed
[4c6aaf53][DevCon Factory Device Farm] Successfully requested the connection for 00008030-001205CC0AF3C02E:9002
[4c6aaf53][AppiumFlutterDriver@2f53] Checking if flutter server is running on port 9020
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][WD Proxy] Matched '/status' to command name 'getStatus'
[4c6aaf53][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9002/status] with no body
[4c6aaf53][iProxy@00008030:9002] Connection was refused to port 9020
[4c6aaf53][WD Proxy] socket hang up
[4c6aaf53][AppiumFlutterDriver@2f53] FlutterServer not reachable on port 9002, Retrying..
[4c6aaf53][DevCon Factory Device Farm] Releasing connections for 00008030-001205CC0AF3C02E device on 9002 port number
[4c6aaf53][DevCon Factory Device Farm] Found cached connections to release: ["00008030-001205CC0AF3C02E:9002"]
[4c6aaf53][DevCon Factory Device Farm] Releasing the listener for '00008030-001205CC0AF3C02E:9002'
[4c6aaf53][iProxy@00008030:9002] Closing the connection
[4c6aaf53][DevCon Factory Device Farm] Cached connections count: 0
[4c6aaf53][iProxy@00008030:9002] The connection has been closed
[4c6aaf53][AppiumDriver@7ecb] Event 'newSessionStarted' logged at 1738174153272 (10:09:13 GMT-0800 (Pacific Standard Time))
[4c6aaf53][AppiumDriver@7ecb] Encountered internal error running command: Error: Flutter server is not started. Please make sure the application under test is configured properly.Please refer https://github.com/AppiumTestDistribution/appium-flutter-integration-driver?tab=readme-ov-file#how-to-use-appium-flutter-integration-driver.
    at AppiumFlutterDriver.createSession (/Users/MOHAPSX18/node_modules/appium-flutter-integration-driver/build/src/driver.js:113:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:384:35)
[4c6aaf53][HTTP] <-- POST /session 500 203407 ms - 1188 

`

**Comment by suryak-cs** [comment]
@sudharsan-selvaraj  here is the appium server log. I have used "appium:flutterSystemPort", 9002. The app opens up and I could see it is trying to search local port 9002, device port 9001. But in the device the appium flutter server always starts at 9000 port. So, how do I fix this issue?
