### ISSUE TITLE
Unable to set text in textfield using Appium Flutter integration driver

### ISSUE THREAD

**Issue by Aruna-gowda** [AppiumTestDistribution/appium-flutter-integration-driver#108]
We are encountering an issue when trying to set text in a text field using the Appium Flutter integration driver. The addValue method does not seem to be working as expected.

error
Error in "My Login application.should login with valid credentials"
Error: Malformed type for "text" parameter of command elementSendKeys
Expected: string
Actual: object

For more info see https://w3c.github.io/webdriver/#dfn-element-send-keys

**Comment by saikrishna321** [comment]
@Aruna-gowda Can you please give ur full server logs and also the device logs. 

Tell us the driver and server version the app is build with.

**Comment by ot-aabbey** [comment]
I am also encountering similar issue.

**Comment by Aruna-gowda** [comment]
> [@Aruna-gowda](https://github.com/Aruna-gowda) Can you please give ur full server logs and also the device logs.
> 
> Tell us the driver and server version the app is build with.

Hi Sai Krishna,

pls find the below details for your reference

**server logs:**

(node:37692) ExperimentalWarning: CommonJS module /opt/homebrew/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /opt/homebrew/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/aruna/testing/rome-appium-integartiontest-1/e2e/node_modules/appium/index.js
/Users/aruna/testing/rome-appium-integartiontest-1/e2e/appium-log.txt

Execution of 1 workers started at 2025-02-04T11:47:41.173Z

2025-02-04T11:47:41.412Z INFO @wdio/cli:launcher: Run onPrepare hook
2025-02-04T11:47:41.415Z INFO @wdio/appium-service: Will spawn Appium process: node /Users/aruna/node_modules/appium/index.js --base-path /wd/hub --log /Users/aruna/testing/rome-appium-integartiontest-1/e2e/appium-logs/log.txt --relaxed-security --address 127.0.0.1 --port 4723
2025-02-04T11:47:43.227Z INFO @wdio/appium-service: Appium started with ID: 37733
2025-02-04T11:47:43.227Z INFO @wdio/appium-service: Appium logs written to stdout
2025-02-04T11:47:43.228Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2025-02-04T11:47:43.229Z INFO @wdio/local-runner: Start worker 0-0 with arg: android.conf.js --spec ./test/specs/test.e2e.js
[0-0] 2025-02-04T11:47:43.760Z INFO @wdio/local-runner: Run worker command: run
[0-0] /Users/aruna/testing/rome-appium-integartiontest-1/e2e/node_modules/appium/index.js
[0-0] /Users/aruna/testing/rome-appium-integartiontest-1/e2e/appium-log.txt
[0-0] RUNNING in Android - file:///test/specs/test.e2e.js
[0-0] 2025-02-04T11:47:44.873Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2025-02-04T11:47:44.873Z INFO @wdio/utils: Connecting to existing driver at http://127.0.0.1:4723/wd/hub
[0-0] 2025-02-04T11:47:44.874Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session
[0-0] 2025-02-04T11:47:44.874Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       platformName: 'Android',
[0-0]       'appium:platformVersion': '11.0',
[0-0]       'appium:automationName': 'FlutterIntegration',
[0-0]       'appium:autoGrantPermissions': true,
[0-0]       'appium:orientation': 'PORTRAIT',
[0-0]       'appium:newCommandTimeout': 1000,
[0-0]       'appium:flutterServerLaunchTimeout': 30000,
[0-0]       'appium:flutterServerConnectionTimeout': 30000,
[0-0]       'appium:flutterServerReadTimeout': 30000,
[0-0]       'appium:flutterElementWaitTimeOut': 30000,
[0-0]       'appium:app': '../build/app/outputs/flutter-apk/app-debug.apk'
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   }
[0-0] }
[0-0] 2025-02-04T11:47:54.732Z INFO webdriver: COMMAND flutterByValueKey$("EmailTextField")
[0-0] 2025-02-04T11:47:54.829Z INFO webdriver: COMMAND flutterByValueKey("key", "EmailTextField")
[0-0] 2025-02-04T11:47:54.830Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session/9cd9d925-2170-4085-8e8a-2c80af2c68b0/element
[0-0] 2025-02-04T11:47:54.831Z INFO webdriver: DATA { using: 'key', value: 'EmailTextField' }
[0-0] 2025-02-04T11:47:55.110Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '3cec48d7-3cec-48d7-3cec-48d73cec48d7',
[0-0]   ELEMENT: '3cec48d7-3cec-48d7-3cec-48d73cec48d7'
[0-0] }
[0-0] 2025-02-04T11:47:55.377Z INFO webdriver: RESULT Element {
[0-0]   sessionId: '9cd9d925-2170-4085-8e8a-2c80af2c68b0',
[0-0]   elementId: '3cec48d7-3cec-48d7-3cec-48d73cec48d7',
[0-0]   ELEMENT: '3cec48d7-3cec-48d7-3cec-48d73cec48d7',
[0-0]   selector: '',
[0-0]   parent: Browser {
[0-0]     sessionId: '9cd9d925-2170-4085-8e8a-2c80af2c68b0',
[0-0]     capabilities: {
[0-0]       subcommand: 'server',
[0-0]       address: '127.0.0.1',
[0-0]       basePath: '/wd/hub',
[0-0]       logFile: '/Users/aruna/testing/rome-appium-integartiontest-1/e2e/appium-logs/log.txt',
[0-0]       port: 4723,
[0-0]       relaxedSecurityEnabled: true,
[0-0]       extraArgs: [],
[0-0]       allowCors: false,
[0-0]       allowInsecure: [],
[0-0]       callbackPort: 4723,
[0-0]       debugLogSpacing: false,
[0-0]       denyInsecure: [],
[0-0]       keepAliveTimeout: 600,
[0-0]       localTimezone: false,
[0-0]       loglevel: 'debug',
[0-0]       logFormat: 'text',
[0-0]       logNoColors: false,
[0-0]       logTimestamp: false,
[0-0]       pluginsImportChunkSize: 7,
[0-0]       driversImportChunkSize: 3,
[0-0]       longStacktrace: false,
[0-0]       noPermsCheck: false,
[0-0]       shutdownTimeout: 5000,
[0-0]       sessionOverride: false,
[0-0]       strictCaps: false,
[0-0]       useDrivers: [],
[0-0]       usePlugins: [],
[0-0]       driver: [Object],
[0-0]       tmpDir: '/var/folders/ct/qpsx2rp14h79t4d4pk2dw81r0000gn/T',
[0-0]       platformName: 'Android',
[0-0]       platformVersion: '11.0',
[0-0]       automationName: 'FlutterIntegration',
[0-0]       autoGrantPermissions: true,
[0-0]       orientation: 'PORTRAIT',
[0-0]       newCommandTimeout: 1000,
[0-0]       flutterServerLaunchTimeout: 30000,
[0-0]       flutterServerConnectionTimeout: 30000,
[0-0]       flutterServerReadTimeout: 30000,
[0-0]       flutterElementWaitTimeOut: 30000,
[0-0]       app: '../build/app/outputs/flutter-apk/app-debug.apk',
[0-0]       fastReset: true,
[0-0]       skipUninstall: true
[0-0]     },
[0-0]     addCommand: [Function (anonymous)],
[0-0]     overwriteCommand: [Function (anonymous)],
[0-0]     addLocatorStrategy: [Function (anonymous)]
[0-0]   },
[0-0]   emit: [Function: bound ],
[0-0]   isReactElement: false,
[0-0]   isShadowElement: false,
[0-0]   addCommand: [Function (anonymous)],
[0-0]   overwriteCommand: [Function (anonymous)]
[0-0] }
[0-0] 2025-02-04T11:47:55.378Z INFO webdriver: COMMAND elementClick("3cec48d7-3cec-48d7-3cec-48d73cec48d7")
[0-0] 2025-02-04T11:47:55.378Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session/9cd9d925-2170-4085-8e8a-2c80af2c68b0/element/3cec48d7-3cec-48d7-3cec-48d73cec48d7/click
[0-0] 2025-02-04T11:47:55.530Z INFO webdriver: RESULT null
[0-0] Error in "My Login application.should login with valid credentials"
Error: Malformed type for "text" parameter of command elementSendKeys
Expected: string
Actual: object

For more info see https://w3c.github.io/webdriver/#dfn-element-send-keys

    at SecurePage.sample (/Users/aruna/testing/rome-appium-integartiontest-1/e2e/test/pageobjects/secure.page.js:15:9)
    at Context.<anonymous> (/Users/aruna/testing/rome-appium-integartiontest-1/e2e/test/specs/test.e2e.js:6:9)
[0-0] 2025-02-04T11:47:57.540Z INFO webdriver: COMMAND deleteSession()
[0-0] 2025-02-04T11:47:57.541Z INFO webdriver: [DELETE] http://127.0.0.1:4723/wd/hub/session/9cd9d925-2170-4085-8e8a-2c80af2c68b0
[0-0] 2025-02-04T11:47:57.803Z INFO webdriver: RESULT null
[0-0] FAILED in Android - file:///test/specs/test.e2e.js
2025-02-04T11:47:57.930Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2025-02-04T11:47:57.931Z INFO @wdio/cli:launcher: Run onComplete hook
2025-02-04T11:47:57.931Z INFO @wdio/appium-service: Killing entire Appium tree

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:16  

2025-02-04T11:47:57.937Z INFO @wdio/local-runner: Shutting down spawned worker
2025-02-04T11:47:57.953Z INFO @wdio/appium-service: Process and its children successfully terminated
2025-02-04T11:47:58.188Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2025-02-04T11:47:58.189Z INFO @wdio/local-runner: shutting down

**Comment by saikrishna321** [comment]
@Aruna-gowda Please share the flutter-integration server and driver version you have used ?

**Comment by Aruna-gowda** [comment]
> [@Aruna-gowda](https://github.com/Aruna-gowda) Please share the flutter-integration server and driver version you have used ?

pls find the below details for your refrence

**Comment by Aruna-gowda** [comment]
> [@Aruna-gowda](https://github.com/Aruna-gowda) what abt the flutter server? Can u please use the latest flutter server and flutter driver and do let u know

@saikrishna321 
"Sure, I'll make sure to use the latest version of the Flutter server and Flutter driver for the automation. I'll update the setup and let you know once it's ready for testing.

**Comment by saikrishna321** [comment]
Don't forget the flutter finder as well.

**Comment by Aruna-gowda** [comment]
> Don't forget the flutter finder as well.

@saikrishna321   I have updated all latest version but still getting same error  and pls find the below details for your reference 

package.json

**Comment by saikrishna321** [comment]
@Aruna-gowda please provide a reproducible app and a code project. This will help speed up the fix.


Here is the sample app which we use for testing and we are unable to reproduce the issue 

https://github.com/AppiumTestDistribution/appium-flutter-server/tree/main/demo-app

**Comment by sudharsan-selvaraj** [comment]
@Aruna-gowda  I have published a new version of `wdio-flutter-by-service`. Could you please give it a try with `v1.1.0`?

NPM- https://www.npmjs.com/package/wdio-flutter-by-service/v/1.1.0

**Comment by Aruna-gowda** [comment]
> [@Aruna-gowda](https://github.com/Aruna-gowda) I have published a new version of `wdio-flutter-by-service`. Could you please give it a try with `v1.1.0`?
> 
> NPM- https://www.npmjs.com/package/wdio-flutter-by-service/v/1.1.0

@sudharsan-selvaraj let me try this

**Comment by Aruna-gowda** [comment]
> > [@Aruna-gowda](https://github.com/Aruna-gowda) I have published a new version of `wdio-flutter-by-service`. Could you please give it a try with `v1.1.0`?
> > NPM- https://www.npmjs.com/package/wdio-flutter-by-service/v/1.1.0
> 
> [@sudharsan-selvaraj](https://github.com/sudharsan-selvaraj) let me try this

@sudharsan-selvaraj  I have updated to "wdio-flutter-by-service v1.1.0", and it is working perfectly. Thank you so much for your effort and time—it truly means a lot!
