### ISSUE TITLE
ScrollUntilVisible options

### ISSUE THREAD

**Issue by thuonglai** [AppiumTestDistribution/appium-flutter-integration-driver#82]
Hi @saikrishna321 . When i call scroll with my setup option as the following code 

```
WebElement scrollable = androidDriver().findElement(FlutterBy.key(axlPickerItem));
        ScrollOptions scrollOptions = new ScrollOptions(FlutterBy.key(axlPickerItem + "_" + index), ScrollOptions.ScrollDirection.UP);
        scrollOptions.setMaxScrolls(50);
        scrollOptions.setScrollView(scrollable);
        WebElement element = FlutterCommands.scrollTillVisible(androidDriver(), scrollOptions);
```
When i add "scrollOptions.setScrollView(scrollable);" it throw exception "org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: type 'Null' is not a subtype of type 'String' in type cast". Please check help me this issue. Thanks.

And this is appium log:
```
[b8a353d4][AppiumFlutterDriver@7288] Calling AppiumDriver.execute() with args: ["flutter: scrollTillVisible",[{"delta":null,"scrollDirection":"up","maxScrolls":50,"scrollView":{"ELEMENT":"2fd2c013-2fd2-c013-2fd2-c0132fd2c013","element-6066-11e4-a52e-4f735466cecf":"2fd2c013-2fd2-c013-2fd2-c0132fd2c013"},"finder":{"strategy":"key","selector":"__axlpicker_item_3"},"settleBetweenScrollsTimeout":null}],"b8a353d4-f279-44f9-b999-c8de4cc00d6d"]
[b8a353d4][WD Proxy] Proxying [POST /session/:sessionId/appium/gestures/scroll_till_visible] to [POST http://127.0.0.1:10001/session/d6699764-5385-4c07-9466-d2654f8a94de/appium/gestures/scroll_till_visible] with body: {"finder":{"strategy":"key","selector":"__axlpicker_item_3"},"scrollView":{"ELEMENT":"2fd2c013-2fd2-c013-2fd2-c0132fd2c013","element-6066-11e4-a52e-4f735466cecf":"2fd2c013-2fd2-c013-2fd2-c0132fd2c013"},"delta":null,"maxScrolls":50,"settleBetweenScrollsTimeout":null,"scrollDirection":"up"}
[b8a353d4][WD Proxy] Got response with status 500: {"sessionId":"d6699764-5385-4c07-9466-d2654f8a94de","value":{"error":"unknown error","message":"type 'Null' is not a subtype of type 'String' in type cast","stackTrace":"#0      new FindElementModel.fromJson (package:appium_flutter_server/src/models/api/find_element.dart:11:55)\n#1      new ScrollTillVisibleModel.fromJson (package:appium_flutter_server/src/models/api/scroll_till_visible.dart:35:32)\n#2      ScrollTillVisibleHandler.handle (package:appium_flutter_server/src/handler/gesture/scroll_till_visible.dart:21:32)\n<asynchronous suspension>\n#3      RequestHandler.getHandler.<anonymous closure> (package:appium_flutter_server/src/handler/request/request_handler.dart:30:35)\n<asynchronous suspension>\n#4      _RouterPlusHandler._handler (package:shelf_plus/src/router_plus/router_plus.dart:64:16)\n<asynchronous suspension>\n#5      RouterEntry.invoke.<anonymous closure> (package:shelf_router/src/router_entry.dart:107:16)\n<asynchronous suspension>\n#6      RouterEntry.invoke (package:shelf_router/src/ro...
[b8a353d4][W3C] Matched W3C error code 'unknown error' to UnknownError
[b8a353d4][AppiumFlutterDriver@7288] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: type 'Null' is not a subtype of type 'String' in type cast
    at errorFromW3CJsonCode (/Users/axlehire/node_modules/@appium/base-driver/lib/protocol/errors.js:1112:25)
    at ProxyRequestError.getActualError (/Users/axlehire/node_modules/@appium/base-driver/lib/protocol/errors.js:981:14)
    at JWProxy.command (/Users/axlehire/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:353:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AppiumFlutterDriver.scrollTillVisible (/Users/axlehire/node_modules/appium-flutter-integration-driver/build/src/driver.js:152:25)
    at AppiumFlutterDriver.executeMethod (/Users/axlehire/node_modules/@appium/base-driver/lib/basedriver/commands/execute.ts:36:12)
    at AppiumFlutterDriver.execute (/Users/axlehire/node_modules/appium-flutter-integration-driver/build/src/driver.js:168:20)
[b8a353d4][HTTP] <-- POST /wd/hub/session/b8a353d4-f279-44f9-b999-c8de4cc00d6d/execute/sync 500 24 ms - 1178 
```

**Comment by saikrishna321** [comment]
@thuonglai Please provide full server logs.

**Comment by thuonglai** [comment]
@saikrishna321 . This is link full log of appium <script src="https://gist.github.com/thuonglai/ef7adae4d17b56825d0a4eb5c406ca35.js"></script>

**Comment by thuonglai** [comment]
Hi @saikrishna321 , do you have any update for this? Thanks

**Comment by saikrishna321** [comment]
@thuonglai Can you please use the latest java-client version 9.3.0. With the latest flutter-server and it should work.
