### ISSUE TITLE
Unable to find ID in the Android app

### ISSUE THREAD

**Issue by erlindadum** [AppiumTestDistribution/appium-flutter-integration-driver#95]
I am trying to target and tap on an element in the Android app but I keep getting an error that says the element cannot be found.

This is the command that is failing:
`app_driver.find_element(AppiumBy.ID, "myAccountTabIdentifier").click()`

And this is the error I get from Appium:
`[d4bc6a3a][HTTP] --> POST /wd/hub/session/d4bc6a3a-d430-435b-b7bb-51f8de9af13f/element {"using":"id","value":"myAccountTabIdentifier"}
[d4bc6a3a][AppiumFlutterDriver@9b00] Calling AppiumDriver.findElement() with args: ["id","myAccountTabIdentifier","d4bc6a3a-d430-435b-b7bb-51f8de9af13f"]
[d4bc6a3a][AppiumFlutterDriver@9b00] Valid locator strategies for this request: xpath, css selector, id, name, class name, -android uiautomator, accessibility id, -ios predicate string, -ios class chain, key, semantics label, text, type, text containing, -flutter key, -flutter semantics label, -flutter text, -flutter type, -flutter text containing
[d4bc6a3a][AndroidUiautomator2Driver@7724] Matched '/element' to command name 'findElement'
[d4bc6a3a][AndroidUiautomator2Driver@7724] Proxying [POST /element] to [POST http://127.0.0.1:8200/session/b28b3110-1304-4f2a-8ca8-f12c6f749e96/element] with body: {"strategy":"id","selector":"myAccountTabIdentifier"}
[d4bc6a3a][AndroidUiautomator2Driver@7724] Got response with status 404: {"sessionId":"b28b3110-1304-4f2a-8ca8-f12c6f749e96","value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters","stacktrace":"io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the page using the given search parameters\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:63)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:259)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:253)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:77)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.chann...
[d4bc6a3a][W3C] Matched W3C error code 'no such element' to NoSuchElementError
[d4bc6a3a][AppiumFlutterDriver@9b00] Encountered internal error running command: io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the page using the given search parameters
	at io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:63)
	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)
	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:259)
	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:253)
	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:77)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:1012)

[d4bc6a3a][HTTP] <-- POST /wd/hub/session/d4bc6a3a-d430-435b-b7bb-51f8de9af13f/element 404 23 ms - 3777`

This is my setup using Pytest:
conftest.py
![Screenshot 2024-09-10 at 2 31 50 PM](https://github.com/user-attachments/assets/17b2a2ea-7cad-4c37-88f2-a1d612b08c59)

test_my_account.py
![Screenshot 2024-09-10 at 2 33 58 PM](https://github.com/user-attachments/assets/ffe71998-8c61-4037-ba93-86f5cdbe47a6)

Additional Notes:

- When running the same command for the iOS app, the click is successful.
- When inspecting the app for the Android app, the ID is there.
<img width="1097" alt="Screenshot 2024-09-10 at 2 38 11 PM" src="https://github.com/user-attachments/assets/189abc10-e31e-4c0d-bd35-56212d671cad">

- When printing app_driver.page_source, the "resource-id" is visible.
<img width="1483" alt="Screenshot 2024-09-10 at 2 37 39 PM" src="https://github.com/user-attachments/assets/62890f7e-9b1e-4899-82af-1f806edd132a">

Versions:
Appium: 2.11.3
flutter-integration: 1.1.3
Appium-Python-Client:  4.1.0

**Comment by sudharsan-selvaraj** [comment]
@erlindadum This issue is not related to the Flutter driver. Native locators are managed by the underlying native drivers (UIAutomator2). Please ensure you include appropriate waits to verify that the element is visible on the screen before attempting to interact with it.

**Comment by erlindadum** [comment]
@sudharsan-selvaraj Thank you for the reply! Your response has led me to the fix here: https://github.com/appium/appium/issues/15138#issuecomment-1127709588
